version: "3.8"

services:
  api:
    container_name: template.api
    user: 1000:1000 # for linux to delete created files
    build:
      context: .
      dockerfile: Dockerfile
      target: template-backend
    command:
      [
        "uvicorn",
        "src.core.main:app",
        "--reload",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
    restart: unless-stopped
    volumes:
      - .:/template
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: bitnami/postgresql:14
    restart: unless-stopped
    container_name: template.postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/bitnami/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 2s
      retries: 10

  api_migrations:
    container_name: template.migrations
    build:
      context: .
      dockerfile: Dockerfile
      target: template-backend
    command: "alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy

  redis:
    container_name: template.redis
    image: bitnami/redis:7.0.1
    ports:
      - "6379:6379"
    env_file:
      - .env
volumes:
  postgres-data:
