FROM python:3.10.4-slim-buster

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# https://github.com/hadolint/hadolint/wiki/DL4006
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN python -m pip install --upgrade pip
RUN python -m pip install flake8 black

COPY . .

RUN black src --check && flake8 --count
