"""table users

Revision ID: 5a8a570fb0c9
Revises: 
Create Date: 2022-10-21 10:29:02.611993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8a570fb0c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Дата обновления записи'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('first_name', sa.String(), nullable=False, comment='Имя пользователя'),
    sa.Column('last_name', sa.String(), nullable=False, comment='Фамилия пользователя2'),
    sa.Column('middle_name', sa.String(), nullable=True, comment='Отчество пользователя'),
    sa.PrimaryKeyConstraint('id'),
    comment='Пользователи'
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
